steps:
  - name: 'ubuntu'
    args: ['ls', '-la', '.']  # Lists the contents of the current directory (build context)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--cache-from=', '-t', 'gcr.io/astute-maxim-458620-r4/github.com/jacobstevens1871/tgtg:$COMMIT_SHA', '.']
    dir: "docker" # Change the directory to the /docker directory
    env:
        - 'DOCKER_BUILDKIT=1'
        - 'CACHE_BUST=$BUILD_ID'  # Or use a timestamp: CACHE_BUST=$(date +%s)
images:
  - 'gcr.io/astute-maxim-458620-r4/github.com/jacobstevens1871/tgtg:$COMMIT_SHA'
options:
  logging: 'CLOUD_LOGGING_ONLY'
